image:
  repository: lancelotmarti/streamlit-example
  tag: latest

service:
  name: streamlit
  port: 8080
  type: NodePort
ingress:
  enabled: true
  className: "" # Will be automatically filled by cluster with "onyxia"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  hosts:
    - host: lancelot-streamlit.lab.sspcloud.fr
      paths:
        - path: /
          pathType: Prefix


imagePullSecrets: []
nameOverride: "streamlit-example"
fullnameOverride: "streamlit-example"

serviceAccount:
  create: false
  annotations: {}
  name: ""
